specVersion: 0.2.0
name: centrifuge-pools
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  endpoint: wss://fullnode-collator-2.development.cntrfg.com
  genesisHash: '0x3e8c9d20daf0eab3deb3a58f71c430dad1ca28a911fab34158792e3eeb77c39b'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handlePoolCreated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: Created
        # - handler: handleInvestOrderUpdated
        #   kind: substrate/EventHandler
        #   filter:
        #     module: pools
        #     method: InvestOrderUpdated
        # - handler: handleRedeemOrderUpdated
        #   kind: substrate/EventHandler
        #   filter:
        #     module: pools
        #     method: RedeemOrderUpdated
        # - handler: handleEpochClosed
        #   kind: substrate/EventHandler
        #   filter:
        #     module: pools
        #     method: EpochClosed
        # - handler: handleEpochExecuted
        #   kind: substrate/EventHandler
        #   filter:
        #     module: pools
        #     method: EpochExecuted
        - handler: handlePoolTotalDebt
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Borrowed
        - handler: handlePoolTotalDebt
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Repaid