specVersion: 1.0.0
name: centrifuge-pools
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: 1.4.1
  query:
    name: '@subql/query'
    version: 1.2.1
description: 'SubQuery API powered by EMBRIO.tech to query Centrifuge chain data for analytics insights on how Centrifuge is unlocking economic opportunity for all by connecting people to borrow and lend money transparently and cost-effectively.'
repository: https://github.com/embrio-tech/centrifuge-subql
schema:
  file: ./schema.graphql
network:
  endpoint: wss://fullnode.development.cntrfg.com
  genesisHash: '0x07f441c88c2fc42afd0f830d2940e9f3245d4297ee7f7713d3da6963fc362be7'
  dictionary: ''
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handlePoolCreated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: Created
        - handler: handleEpochClosed
          kind: substrate/EventHandler
          filter:
            module: pools
            method: EpochClosed
        - handler: handleEpochExecuted
          kind: substrate/EventHandler
          filter:
            module: pools
            method: EpochExecuted
        - handler: handleInvestOrderUpdated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: InvestOrderUpdated
        - handler: handleRedeemOrderUpdated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: RedeemOrderUpdated
        - handler: handleOrdersCollected
          kind: substrate/EventHandler
          filter:
            module: pools
            method: OrdersCollected
        - handler: handleProxyAdded
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: ProxyAdded
        - handler: handleProxyRemoved
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: ProxyRemoved
        - handler: handleProxyAnonymousCreated
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: AnonymousCreated
        - handler: handleBorrowings
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Borrowed
