specVersion: 0.2.0
name: centrifuge-pools
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  endpoint: wss://fullnode.development.cntrfg.com
  genesisHash: '0x31eae49488ddf60b2ae2829e5bb9e2ae67aef01756fd8ee0e6c63fe85b603774'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handlePoolCreated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: Created
        - handler: handleEpochClosed
          kind: substrate/EventHandler
          filter:
            module: pools
            method: EpochClosed
        - handler: handleEpochExecuted
          kind: substrate/EventHandler
          filter:
            module: pools
            method: EpochExecuted
        - handler: handleInvestOrderUpdated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: InvestOrderUpdated
        - handler: handleRedeemOrderUpdated
          kind: substrate/EventHandler
          filter:
            module: pools
            method: RedeemOrderUpdated
        - handler: handleProxyAdded
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: ProxyAdded
        - handler: handleProxyRemoved
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: ProxyRemoved
        - handler: handleProxyAnonymousCreated
          kind: substrate/EventHandler
          filter:
            module: proxy
            method: AnonymousCreated
        - handler: handleBorrowings
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Borrowed
