name: 'Test'
on:
  pull_request:
    branches:    
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    name: 'Check Build'
    runs-on: ubuntu-latest
    env:
      SUBQL_INDEXER_VERSION: v3.4.7
      SUBQL_QUERY_VERSION: v2.6.0
      CHAIN_ID: demo
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Generate new project-centrifuge.yaml
        run: yq ". *=d load(\"chains-cfg/$CHAIN_ID.yaml\")" chains-cfg/base.yaml > project-centrifuge.yaml
      - name: Generate new project-ethereum.yaml
        run: yq ". *=d load(\"chains-eth/$CHAIN_ID.yaml\")" chains-eth/base.yaml | envsubst > project-ethereum.yaml
      - name: Generate new project-coinbase.yaml
        run: yq ". *=d load(\"chains-base/$CHAIN_ID.yaml\")" chains-eth/base.yaml | envsubst > project-coinbase.yaml
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Setup Yarn
        run: yarn install --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build

  lint:
    name: 'Run Linter'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Initialise project.yaml
        run: cp chains-cfg/base.yaml project.yaml
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 'Install Dependencies'
        run: yarn install
      - name: 'Generate Entities'
        run: yarn codegen
      - name: 'Run Linter'
        run: yarn lint
  test:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Initialise project.yaml
        run: cp chains-cfg/base.yaml project.yaml
      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 'Install Dependencies'
        run: yarn install
      - name: 'Generate Entities'
        run: yarn codegen
      - name: 'Run Tests'
        run: yarn test
